# Generated by Django 3.1.3 on 2020-11-16 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountspace', '0003_auto_20201114_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('starting_year', models.DateField()),
                ('end_year', models.DateField()),
                ('employment_relationship', models.CharField(max_length=128)),
                ('industry', models.CharField(max_length=128)),
                ('supervisor', models.CharField(max_length=128)),
                ('specialisation', models.CharField(max_length=128)),
                ('task_description', models.TextField()),
                ('company_address', models.TextField()),
                ('avg_weekly_working_time', models.IntegerField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountspace.bewerber')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=128)),
                ('name_of_degree', models.CharField(max_length=128)),
                ('type_of_degree', models.CharField(choices=[('bsc', 'Master of Science'), ('ma', 'Master of Arts'), ('bsc', 'Bachelor of Science'), ('ba', 'Bachelor of Arts')], max_length=3)),
                ('specialisation', models.CharField(max_length=128)),
                ('graduation_date', models.DateField()),
                ('starting_date', models.DateField()),
                ('no_of_semesters', models.IntegerField()),
                ('avg_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountspace.bewerber')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDegrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('type_of_degree', models.CharField(max_length=128)),
                ('graduation_year', models.DateField()),
                ('starting_year', models.DateField()),
                ('avg_score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountspace.bewerber')),
            ],
        ),
        migrations.CreateModel(
            name='Bewerbung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateTimeField(auto_created=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined')], max_length=1)),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountspace.bewerber')),
                ('school_degrees', models.ManyToManyField(to='admissionspace.SchoolDegrees')),
                ('uni_degrees', models.ManyToManyField(to='admissionspace.UniversityDegree')),
                ('work_experiences', models.ManyToManyField(to='admissionspace.WorkExperience')),
            ],
        ),
    ]
