# Generated by Django 3.1.3 on 2020-11-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountspace', '0003_auto_20201114_1221'),
        ('admissionspace', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolDegrees',
            new_name='SchoolDegree',
        ),
    ]
