# Generated by Django 3.1.3 on 2020-11-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissionspace', '0004_auto_20201116_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooldegree',
            old_name='starting_year',
            new_name='starting_date',
        ),
    ]
