# Generated by Django 3.1.3 on 2020-11-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionspace', '0005_auto_20201116_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewerbung',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('D', 'Declined')], default='P', max_length=1),
        ),
    ]
