# Generated by Django 3.1.3 on 2020-11-18 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissionspace', '0006_auto_20201116_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitydegree',
            name='type_of_degree',
            field=models.CharField(choices=[('msc', 'Master of Science'), ('ma', 'Master of Arts'), ('bsc', 'Bachelor of Science'), ('ba', 'Bachelor of Arts')], max_length=3),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('job_position', models.CharField(default='', max_length=40)),
                ('company_name', models.CharField(max_length=128)),
                ('company_address', models.TextField()),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=12)),
                ('available_from', models.TimeField()),
                ('available_until', models.TimeField()),
                ('recommendation_letter', models.TextField()),
                ('bewerber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
