# Generated by Django 3.1.3 on 2020-11-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissionspace', '0007_auto_20201118_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bewerbung',
            name='uni_degrees',
            field=models.ManyToManyField(blank=True, to='admissionspace.UniversityDegree'),
        ),
        migrations.AlterField(
            model_name='bewerbung',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, to='admissionspace.WorkExperience'),
        ),
    ]
