# Generated by Django 3.1.3 on 2020-11-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bewerber',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accountspace.user')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('street', models.CharField(default='', max_length=30)),
                ('post_code', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
