# Generated by Django 3.1.3 on 2020-11-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountspace', '0002_bewerber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bewerber',
            old_name='user_id',
            new_name='user',
        ),
    ]
